# Generated by Django 5.2.5 on 2025-08-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extras',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
