# Generated by Django 5.2.5 on 2025-08-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_remove_booking_slot_booking_desired_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
