--
-- PostgreSQL database dump
--

-- Dumped from database version 16.3
-- Dumped by pg_dump version 16.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO postgres;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO postgres;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_customuser (
    id bigint NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    username character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    extras jsonb NOT NULL,
    phone_number character varying(15)
);


ALTER TABLE public.authentication_customuser OWNER TO postgres;

--
-- Name: authentication_customuser_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.authentication_customuser_groups OWNER TO postgres;

--
-- Name: authentication_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authentication_customuser_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authentication_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.authentication_customuser_user_permissions OWNER TO postgres;

--
-- Name: authentication_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.authentication_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authentication_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_clockedschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_clockedschedule (
    id integer NOT NULL,
    clocked_time timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_clockedschedule OWNER TO postgres;

--
-- Name: django_celery_beat_clockedschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_clockedschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_clockedschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_crontabschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_crontabschedule (
    id integer NOT NULL,
    minute character varying(240) NOT NULL,
    hour character varying(96) NOT NULL,
    day_of_week character varying(64) NOT NULL,
    day_of_month character varying(124) NOT NULL,
    month_of_year character varying(64) NOT NULL,
    timezone character varying(63) NOT NULL
);


ALTER TABLE public.django_celery_beat_crontabschedule OWNER TO postgres;

--
-- Name: django_celery_beat_crontabschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_crontabschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_crontabschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_intervalschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_intervalschedule (
    id integer NOT NULL,
    every integer NOT NULL,
    period character varying(24) NOT NULL
);


ALTER TABLE public.django_celery_beat_intervalschedule OWNER TO postgres;

--
-- Name: django_celery_beat_intervalschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_intervalschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_intervalschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictask; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictask (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    task character varying(200) NOT NULL,
    args text NOT NULL,
    kwargs text NOT NULL,
    queue character varying(200),
    exchange character varying(200),
    routing_key character varying(200),
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_expire_seconds_check CHECK ((expire_seconds >= 0)),
    CONSTRAINT django_celery_beat_periodictask_priority_check CHECK ((priority >= 0)),
    CONSTRAINT django_celery_beat_periodictask_total_run_count_check CHECK ((total_run_count >= 0))
);


ALTER TABLE public.django_celery_beat_periodictask OWNER TO postgres;

--
-- Name: django_celery_beat_periodictask_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_periodictask ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_periodictask_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_beat_periodictasks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_periodictasks (
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL
);


ALTER TABLE public.django_celery_beat_periodictasks OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_beat_solarschedule (
    id integer NOT NULL,
    event character varying(24) NOT NULL,
    latitude numeric(9,6) NOT NULL,
    longitude numeric(9,6) NOT NULL
);


ALTER TABLE public.django_celery_beat_solarschedule OWNER TO postgres;

--
-- Name: django_celery_beat_solarschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_beat_solarschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_beat_solarschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_chordcounter; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_chordcounter (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    sub_tasks text NOT NULL,
    count integer NOT NULL,
    CONSTRAINT django_celery_results_chordcounter_count_check CHECK ((count >= 0))
);


ALTER TABLE public.django_celery_results_chordcounter OWNER TO postgres;

--
-- Name: django_celery_results_chordcounter_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_chordcounter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_chordcounter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_groupresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_groupresult (
    id integer NOT NULL,
    group_id character varying(255) NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_done timestamp with time zone NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text
);


ALTER TABLE public.django_celery_results_groupresult OWNER TO postgres;

--
-- Name: django_celery_results_groupresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_groupresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_groupresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_celery_results_taskresult; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_celery_results_taskresult (
    id integer NOT NULL,
    task_id character varying(255) NOT NULL,
    status character varying(50) NOT NULL,
    content_type character varying(128) NOT NULL,
    content_encoding character varying(64) NOT NULL,
    result text,
    date_done timestamp with time zone NOT NULL,
    traceback text,
    meta text,
    task_args text,
    task_kwargs text,
    task_name character varying(255),
    worker character varying(100),
    date_created timestamp with time zone NOT NULL,
    periodic_task_name character varying(255),
    date_started timestamp with time zone
);


ALTER TABLE public.django_celery_results_taskresult OWNER TO postgres;

--
-- Name: django_celery_results_taskresult_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_celery_results_taskresult ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_celery_results_taskresult_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO postgres;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token_refreshtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token_refreshtoken (
    id bigint NOT NULL,
    token character varying(255) NOT NULL,
    created timestamp with time zone NOT NULL,
    revoked timestamp with time zone,
    user_id bigint NOT NULL
);


ALTER TABLE public.refresh_token_refreshtoken OWNER TO postgres;

--
-- Name: refresh_token_refreshtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token_refreshtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_refreshtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slots_booking; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.slots_booking (
    id uuid NOT NULL,
    booking_date timestamp with time zone NOT NULL,
    status character varying(20) NOT NULL,
    details jsonb,
    payment_transaction_id uuid,
    wallet_id uuid NOT NULL,
    desired_time timestamp with time zone,
    schedule_id bigint
);


ALTER TABLE public.slots_booking OWNER TO postgres;

--
-- Name: slots_slot; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.slots_slot (
    id uuid NOT NULL,
    title character varying(255) NOT NULL,
    description jsonb,
    action jsonb,
    fields jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slot_type_id uuid NOT NULL,
    cover_image character varying(100),
    owner_id bigint NOT NULL
);


ALTER TABLE public.slots_slot OWNER TO postgres;

--
-- Name: slots_slot_collaborators; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.slots_slot_collaborators (
    id bigint NOT NULL,
    slot_id uuid NOT NULL,
    customuser_id bigint NOT NULL
);


ALTER TABLE public.slots_slot_collaborators OWNER TO postgres;

--
-- Name: slots_slot_collaborators_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.slots_slot_collaborators ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.slots_slot_collaborators_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slots_slotschedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.slots_slotschedule (
    id bigint NOT NULL,
    start_time timestamp with time zone,
    duration_minutes integer NOT NULL,
    grace_period_minutes integer NOT NULL,
    recurring boolean NOT NULL,
    recurrence_pattern jsonb,
    flexible boolean NOT NULL,
    slot_id uuid NOT NULL,
    price numeric(20,2) NOT NULL,
    CONSTRAINT slots_slotschedule_duration_minutes_check CHECK ((duration_minutes >= 0)),
    CONSTRAINT slots_slotschedule_grace_period_minutes_check CHECK ((grace_period_minutes >= 0))
);


ALTER TABLE public.slots_slotschedule OWNER TO postgres;

--
-- Name: slots_slotschedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.slots_slotschedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.slots_slotschedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: slots_slottype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.slots_slottype (
    id uuid NOT NULL,
    name character varying(100) NOT NULL,
    frequency integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT slots_slottype_frequency_check CHECK ((frequency >= 0))
);


ALTER TABLE public.slots_slottype OWNER TO postgres;

--
-- Name: socialaccount_socialaccount; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialaccount (
    id integer NOT NULL,
    provider character varying(200) NOT NULL,
    uid character varying(191) NOT NULL,
    last_login timestamp with time zone NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    extra_data jsonb NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.socialaccount_socialaccount OWNER TO postgres;

--
-- Name: socialaccount_socialaccount_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialaccount ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialaccount_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialapp (
    id integer NOT NULL,
    provider character varying(30) NOT NULL,
    name character varying(40) NOT NULL,
    client_id character varying(191) NOT NULL,
    secret character varying(191) NOT NULL,
    key character varying(191) NOT NULL,
    provider_id character varying(200) NOT NULL,
    settings jsonb NOT NULL
);


ALTER TABLE public.socialaccount_socialapp OWNER TO postgres;

--
-- Name: socialaccount_socialapp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialapp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialapp_sites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialapp_sites (
    id bigint NOT NULL,
    socialapp_id integer NOT NULL,
    site_id integer NOT NULL
);


ALTER TABLE public.socialaccount_socialapp_sites OWNER TO postgres;

--
-- Name: socialaccount_socialapp_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialapp_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialapp_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: socialaccount_socialtoken; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.socialaccount_socialtoken (
    id integer NOT NULL,
    token text NOT NULL,
    token_secret text NOT NULL,
    expires_at timestamp with time zone,
    account_id integer NOT NULL,
    app_id integer
);


ALTER TABLE public.socialaccount_socialtoken OWNER TO postgres;

--
-- Name: socialaccount_socialtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.socialaccount_socialtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.socialaccount_socialtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_location; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_location (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    address text,
    latitude numeric(9,6),
    longitude numeric(9,6),
    location_type_id bigint NOT NULL
);


ALTER TABLE public.wallet_location OWNER TO postgres;

--
-- Name: wallet_location_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_locationtype; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_locationtype (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description text
);


ALTER TABLE public.wallet_locationtype OWNER TO postgres;

--
-- Name: wallet_locationtype_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_locationtype ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_locationtype_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_passcategory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_passcategory (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description text
);


ALTER TABLE public.wallet_passcategory OWNER TO postgres;

--
-- Name: wallet_passcategory_allowed_location_types; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_passcategory_allowed_location_types (
    id bigint NOT NULL,
    passcategory_id bigint NOT NULL,
    locationtype_id bigint NOT NULL
);


ALTER TABLE public.wallet_passcategory_allowed_location_types OWNER TO postgres;

--
-- Name: wallet_passcategory_allowed_location_types_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_passcategory_allowed_location_types ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_passcategory_allowed_location_types_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_passcategory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_passcategory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_passcategory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_passdetails; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_passdetails (
    id bigint NOT NULL,
    start_date date,
    end_date date,
    category_id bigint NOT NULL,
    from_location_id bigint,
    to_location_id bigint,
    wallet_id uuid NOT NULL,
    name character varying(255)
);


ALTER TABLE public.wallet_passdetails OWNER TO postgres;

--
-- Name: wallet_passdetails_allowed_locations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_passdetails_allowed_locations (
    id bigint NOT NULL,
    passdetails_id bigint NOT NULL,
    location_id bigint NOT NULL
);


ALTER TABLE public.wallet_passdetails_allowed_locations OWNER TO postgres;

--
-- Name: wallet_passdetails_allowed_locations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_passdetails_allowed_locations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_passdetails_allowed_locations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_passdetails_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.wallet_passdetails ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_passdetails_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_transaction (
    transaction_id uuid NOT NULL,
    amount numeric(20,2) NOT NULL,
    transaction_date timestamp with time zone NOT NULL,
    transaction_type character varying(50) NOT NULL,
    status character varying(20) NOT NULL,
    description text,
    from_wallet_id uuid,
    to_wallet_id uuid
);


ALTER TABLE public.wallet_transaction OWNER TO postgres;

--
-- Name: wallet_wallet; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.wallet_wallet (
    wallet_id uuid NOT NULL,
    balance numeric(20,2) NOT NULL,
    wallet_type character varying(20) NOT NULL,
    access_qr_code character varying(255),
    access_nfc_code character varying(255),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    parent_wallet_id uuid,
    user_id bigint NOT NULL,
    name character varying(100),
    exp_date date
);


ALTER TABLE public.wallet_wallet OWNER TO postgres;

--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_groups authentication_customuse_customuser_id_group_id_8a637646_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuse_customuser_id_group_id_8a637646_uniq UNIQUE (customuser_id, group_id);


--
-- Name: authentication_customuser_user_permissions authentication_customuse_customuser_id_permission_923704b1_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuse_customuser_id_permission_923704b1_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: authentication_customuser authentication_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_email_key UNIQUE (email);


--
-- Name: authentication_customuser_groups authentication_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser authentication_customuser_phone_number_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_phone_number_key UNIQUE (phone_number);


--
-- Name: authentication_customuser authentication_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser
    ADD CONSTRAINT authentication_customuser_pkey PRIMARY KEY (id);


--
-- Name: authentication_customuser_user_permissions authentication_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_clockedschedule django_celery_beat_clockedschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_clockedschedule
    ADD CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_crontabschedule django_celery_beat_crontabschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_crontabschedule
    ADD CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_intervalschedule django_celery_beat_intervalschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_intervalschedule
    ADD CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name);


--
-- Name: django_celery_beat_periodictask django_celery_beat_periodictask_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id);


--
-- Name: django_celery_beat_periodictasks django_celery_beat_periodictasks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictasks
    ADD CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude);


--
-- Name: django_celery_beat_solarschedule django_celery_beat_solarschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_solarschedule
    ADD CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_chordcounter django_celery_results_chordcounter_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_chordcounter
    ADD CONSTRAINT django_celery_results_chordcounter_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_group_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_group_id_key UNIQUE (group_id);


--
-- Name: django_celery_results_groupresult django_celery_results_groupresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_groupresult
    ADD CONSTRAINT django_celery_results_groupresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_pkey PRIMARY KEY (id);


--
-- Name: django_celery_results_taskresult django_celery_results_taskresult_task_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_results_taskresult
    ADD CONSTRAINT django_celery_results_taskresult_task_id_key UNIQUE (task_id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: refresh_token_refreshtoken refresh_token_refreshtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token_refreshtoken
    ADD CONSTRAINT refresh_token_refreshtoken_pkey PRIMARY KEY (id);


--
-- Name: refresh_token_refreshtoken refresh_token_refreshtoken_token_revoked_b683a545_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token_refreshtoken
    ADD CONSTRAINT refresh_token_refreshtoken_token_revoked_b683a545_uniq UNIQUE (token, revoked);


--
-- Name: slots_booking slots_booking_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_booking
    ADD CONSTRAINT slots_booking_pkey PRIMARY KEY (id);


--
-- Name: slots_slot_collaborators slots_slot_collaborators_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slot_collaborators
    ADD CONSTRAINT slots_slot_collaborators_pkey PRIMARY KEY (id);


--
-- Name: slots_slot_collaborators slots_slot_collaborators_slot_id_customuser_id_478fb6aa_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slot_collaborators
    ADD CONSTRAINT slots_slot_collaborators_slot_id_customuser_id_478fb6aa_uniq UNIQUE (slot_id, customuser_id);


--
-- Name: slots_slot slots_slot_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slot
    ADD CONSTRAINT slots_slot_pkey PRIMARY KEY (id);


--
-- Name: slots_slotschedule slots_slotschedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slotschedule
    ADD CONSTRAINT slots_slotschedule_pkey PRIMARY KEY (id);


--
-- Name: slots_slottype slots_slottype_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slottype
    ADD CONSTRAINT slots_slottype_name_key UNIQUE (name);


--
-- Name: slots_slottype slots_slottype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slottype
    ADD CONSTRAINT slots_slottype_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialaccount socialaccount_socialaccount_provider_uid_fc810c6e_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_socialaccount_provider_uid_fc810c6e_uniq UNIQUE (provider, uid);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp__socialapp_id_site_id_71a9a768_uniq UNIQUE (socialapp_id, site_id);


--
-- Name: socialaccount_socialapp socialaccount_socialapp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp
    ADD CONSTRAINT socialaccount_socialapp_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialapp_sites socialaccount_socialapp_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_socialapp_sites_pkey PRIMARY KEY (id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq UNIQUE (app_id, account_id);


--
-- Name: socialaccount_socialtoken socialaccount_socialtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_socialtoken_pkey PRIMARY KEY (id);


--
-- Name: wallet_location wallet_location_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_location
    ADD CONSTRAINT wallet_location_pkey PRIMARY KEY (id);


--
-- Name: wallet_locationtype wallet_locationtype_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_locationtype
    ADD CONSTRAINT wallet_locationtype_name_key UNIQUE (name);


--
-- Name: wallet_locationtype wallet_locationtype_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_locationtype
    ADD CONSTRAINT wallet_locationtype_pkey PRIMARY KEY (id);


--
-- Name: wallet_passcategory_allowed_location_types wallet_passcategory_allo_passcategory_id_location_e1f558b4_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passcategory_allowed_location_types
    ADD CONSTRAINT wallet_passcategory_allo_passcategory_id_location_e1f558b4_uniq UNIQUE (passcategory_id, locationtype_id);


--
-- Name: wallet_passcategory_allowed_location_types wallet_passcategory_allowed_location_types_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passcategory_allowed_location_types
    ADD CONSTRAINT wallet_passcategory_allowed_location_types_pkey PRIMARY KEY (id);


--
-- Name: wallet_passcategory wallet_passcategory_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passcategory
    ADD CONSTRAINT wallet_passcategory_name_key UNIQUE (name);


--
-- Name: wallet_passcategory wallet_passcategory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passcategory
    ADD CONSTRAINT wallet_passcategory_pkey PRIMARY KEY (id);


--
-- Name: wallet_passdetails_allowed_locations wallet_passdetails_allow_passdetails_id_location__01349f77_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails_allowed_locations
    ADD CONSTRAINT wallet_passdetails_allow_passdetails_id_location__01349f77_uniq UNIQUE (passdetails_id, location_id);


--
-- Name: wallet_passdetails_allowed_locations wallet_passdetails_allowed_locations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails_allowed_locations
    ADD CONSTRAINT wallet_passdetails_allowed_locations_pkey PRIMARY KEY (id);


--
-- Name: wallet_passdetails wallet_passdetails_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails
    ADD CONSTRAINT wallet_passdetails_pkey PRIMARY KEY (id);


--
-- Name: wallet_passdetails wallet_passdetails_wallet_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails
    ADD CONSTRAINT wallet_passdetails_wallet_id_key UNIQUE (wallet_id);


--
-- Name: wallet_transaction wallet_transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_transaction
    ADD CONSTRAINT wallet_transaction_pkey PRIMARY KEY (transaction_id);


--
-- Name: wallet_wallet wallet_wallet_access_nfc_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_access_nfc_code_key UNIQUE (access_nfc_code);


--
-- Name: wallet_wallet wallet_wallet_access_qr_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_access_qr_code_key UNIQUE (access_qr_code);


--
-- Name: wallet_wallet wallet_wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_pkey PRIMARY KEY (wallet_id);


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authentication_customuser__customuser_id_33d2a5f7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser__customuser_id_33d2a5f7 ON public.authentication_customuser_user_permissions USING btree (customuser_id);


--
-- Name: authentication_customuser__permission_id_e47332af; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser__permission_id_e47332af ON public.authentication_customuser_user_permissions USING btree (permission_id);


--
-- Name: authentication_customuser_email_a127f886_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_email_a127f886_like ON public.authentication_customuser USING btree (email varchar_pattern_ops);


--
-- Name: authentication_customuser_groups_customuser_id_a7d1343c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_groups_customuser_id_a7d1343c ON public.authentication_customuser_groups USING btree (customuser_id);


--
-- Name: authentication_customuser_groups_group_id_c5ef1d10; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_groups_group_id_c5ef1d10 ON public.authentication_customuser_groups USING btree (group_id);


--
-- Name: authentication_customuser_phone_number_3b3c25bb_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authentication_customuser_phone_number_3b3c25bb_like ON public.authentication_customuser USING btree (phone_number varchar_pattern_ops);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_cele_date_cr_bd6c1d_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_cr_bd6c1d_idx ON public.django_celery_results_groupresult USING btree (date_created);


--
-- Name: django_cele_date_cr_f04a50_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_cr_f04a50_idx ON public.django_celery_results_taskresult USING btree (date_created);


--
-- Name: django_cele_date_do_caae0e_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_do_caae0e_idx ON public.django_celery_results_groupresult USING btree (date_done);


--
-- Name: django_cele_date_do_f59aad_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_date_do_f59aad_idx ON public.django_celery_results_taskresult USING btree (date_done);


--
-- Name: django_cele_periodi_1993cf_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_periodi_1993cf_idx ON public.django_celery_results_taskresult USING btree (periodic_task_name);


--
-- Name: django_cele_status_9b6201_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_status_9b6201_idx ON public.django_celery_results_taskresult USING btree (status);


--
-- Name: django_cele_task_na_08aec9_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_task_na_08aec9_idx ON public.django_celery_results_taskresult USING btree (task_name);


--
-- Name: django_cele_worker_d54dd8_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_cele_worker_d54dd8_idx ON public.django_celery_results_taskresult USING btree (worker);


--
-- Name: django_celery_beat_periodictask_clocked_id_47a69f82; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_clocked_id_47a69f82 ON public.django_celery_beat_periodictask USING btree (clocked_id);


--
-- Name: django_celery_beat_periodictask_crontab_id_d3cba168; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_crontab_id_d3cba168 ON public.django_celery_beat_periodictask USING btree (crontab_id);


--
-- Name: django_celery_beat_periodictask_interval_id_a8ca27da; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_interval_id_a8ca27da ON public.django_celery_beat_periodictask USING btree (interval_id);


--
-- Name: django_celery_beat_periodictask_name_265a36b7_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_name_265a36b7_like ON public.django_celery_beat_periodictask USING btree (name varchar_pattern_ops);


--
-- Name: django_celery_beat_periodictask_solar_id_a87ce72c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_beat_periodictask_solar_id_a87ce72c ON public.django_celery_beat_periodictask USING btree (solar_id);


--
-- Name: django_celery_results_chordcounter_group_id_1f70858c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_chordcounter_group_id_1f70858c_like ON public.django_celery_results_chordcounter USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_groupresult_group_id_a085f1a9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_groupresult_group_id_a085f1a9_like ON public.django_celery_results_groupresult USING btree (group_id varchar_pattern_ops);


--
-- Name: django_celery_results_taskresult_task_id_de0d95bf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_celery_results_taskresult_task_id_de0d95bf_like ON public.django_celery_results_taskresult USING btree (task_id varchar_pattern_ops);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: refresh_token_refreshtoken_user_id_45383307; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX refresh_token_refreshtoken_user_id_45383307 ON public.refresh_token_refreshtoken USING btree (user_id);


--
-- Name: slots_booking_payment_transaction_id_1f4d1fe8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_booking_payment_transaction_id_1f4d1fe8 ON public.slots_booking USING btree (payment_transaction_id);


--
-- Name: slots_booking_schedule_id_688b7970; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_booking_schedule_id_688b7970 ON public.slots_booking USING btree (schedule_id);


--
-- Name: slots_booking_wallet_id_3e3b637f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_booking_wallet_id_3e3b637f ON public.slots_booking USING btree (wallet_id);


--
-- Name: slots_slot_collaborators_customuser_id_04c742ac; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_slot_collaborators_customuser_id_04c742ac ON public.slots_slot_collaborators USING btree (customuser_id);


--
-- Name: slots_slot_collaborators_slot_id_41e1f6c2; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_slot_collaborators_slot_id_41e1f6c2 ON public.slots_slot_collaborators USING btree (slot_id);


--
-- Name: slots_slot_owner_id_903fd48f; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_slot_owner_id_903fd48f ON public.slots_slot USING btree (owner_id);


--
-- Name: slots_slot_slot_type_id_2afde436; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_slot_slot_type_id_2afde436 ON public.slots_slot USING btree (slot_type_id);


--
-- Name: slots_slotschedule_slot_id_087c7c21; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_slotschedule_slot_id_087c7c21 ON public.slots_slotschedule USING btree (slot_id);


--
-- Name: slots_slottype_name_590f742b_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slots_slottype_name_590f742b_like ON public.slots_slottype USING btree (name varchar_pattern_ops);


--
-- Name: socialaccount_socialaccount_user_id_8146e70c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialaccount_user_id_8146e70c ON public.socialaccount_socialaccount USING btree (user_id);


--
-- Name: socialaccount_socialapp_sites_site_id_2579dee5; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialapp_sites_site_id_2579dee5 ON public.socialaccount_socialapp_sites USING btree (site_id);


--
-- Name: socialaccount_socialapp_sites_socialapp_id_97fb6e7d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialapp_sites_socialapp_id_97fb6e7d ON public.socialaccount_socialapp_sites USING btree (socialapp_id);


--
-- Name: socialaccount_socialtoken_account_id_951f210e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialtoken_account_id_951f210e ON public.socialaccount_socialtoken USING btree (account_id);


--
-- Name: socialaccount_socialtoken_app_id_636a42d7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX socialaccount_socialtoken_app_id_636a42d7 ON public.socialaccount_socialtoken USING btree (app_id);


--
-- Name: unique_main_wallet_per_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_main_wallet_per_user ON public.wallet_wallet USING btree (user_id, wallet_type) WHERE ((wallet_type)::text = 'main'::text);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: wallet_location_location_type_id_03e38010; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_location_location_type_id_03e38010 ON public.wallet_location USING btree (location_type_id);


--
-- Name: wallet_locationtype_name_e4c927a6_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_locationtype_name_e4c927a6_like ON public.wallet_locationtype USING btree (name varchar_pattern_ops);


--
-- Name: wallet_passcategory_allowe_locationtype_id_e49c1689; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passcategory_allowe_locationtype_id_e49c1689 ON public.wallet_passcategory_allowed_location_types USING btree (locationtype_id);


--
-- Name: wallet_passcategory_allowe_passcategory_id_c04f7a32; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passcategory_allowe_passcategory_id_c04f7a32 ON public.wallet_passcategory_allowed_location_types USING btree (passcategory_id);


--
-- Name: wallet_passcategory_name_c47b5c4d_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passcategory_name_c47b5c4d_like ON public.wallet_passcategory USING btree (name varchar_pattern_ops);


--
-- Name: wallet_passdetails_allowed_locations_location_id_417b4b4d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passdetails_allowed_locations_location_id_417b4b4d ON public.wallet_passdetails_allowed_locations USING btree (location_id);


--
-- Name: wallet_passdetails_allowed_locations_passdetails_id_8d5ddd88; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passdetails_allowed_locations_passdetails_id_8d5ddd88 ON public.wallet_passdetails_allowed_locations USING btree (passdetails_id);


--
-- Name: wallet_passdetails_category_id_5a7d0ab9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passdetails_category_id_5a7d0ab9 ON public.wallet_passdetails USING btree (category_id);


--
-- Name: wallet_passdetails_from_location_id_b3ebddd6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passdetails_from_location_id_b3ebddd6 ON public.wallet_passdetails USING btree (from_location_id);


--
-- Name: wallet_passdetails_to_location_id_e81ab599; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_passdetails_to_location_id_e81ab599 ON public.wallet_passdetails USING btree (to_location_id);


--
-- Name: wallet_transaction_from_wallet_id_cc4434bf; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_transaction_from_wallet_id_cc4434bf ON public.wallet_transaction USING btree (from_wallet_id);


--
-- Name: wallet_transaction_to_wallet_id_6fd62e93; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_transaction_to_wallet_id_6fd62e93 ON public.wallet_transaction USING btree (to_wallet_id);


--
-- Name: wallet_wallet_access_nfc_code_b473d1c9_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_wallet_access_nfc_code_b473d1c9_like ON public.wallet_wallet USING btree (access_nfc_code varchar_pattern_ops);


--
-- Name: wallet_wallet_access_qr_code_135dcfbf_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_wallet_access_qr_code_135dcfbf_like ON public.wallet_wallet USING btree (access_qr_code varchar_pattern_ops);


--
-- Name: wallet_wallet_parent_wallet_id_7a48dbf4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_wallet_parent_wallet_id_7a48dbf4 ON public.wallet_wallet USING btree (parent_wallet_id);


--
-- Name: wallet_wallet_user_id_8c75caaa; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX wallet_wallet_user_id_8c75caaa ON public.wallet_wallet USING btree (user_id);


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_customuser_id_33d2a5f7_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_customuser_id_33d2a5f7_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_customuser_id_a7d1343c_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_customuser_id_a7d1343c_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_groups authentication_custo_group_id_c5ef1d10_fk_auth_grou; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_groups
    ADD CONSTRAINT authentication_custo_group_id_c5ef1d10_fk_auth_grou FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authentication_customuser_user_permissions authentication_custo_permission_id_e47332af_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authentication_customuser_user_permissions
    ADD CONSTRAINT authentication_custo_permission_id_e47332af_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_clocked_id_47a69f82_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id) REFERENCES public.django_celery_beat_clockedschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_crontab_id_d3cba168_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id) REFERENCES public.django_celery_beat_crontabschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_interval_id_a8ca27da_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id) REFERENCES public.django_celery_beat_intervalschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_celery_beat_periodictask django_celery_beat_p_solar_id_a87ce72c_fk_django_ce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id) REFERENCES public.django_celery_beat_solarschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: refresh_token_refreshtoken refresh_token_refres_user_id_45383307_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token_refreshtoken
    ADD CONSTRAINT refresh_token_refres_user_id_45383307_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_booking slots_booking_payment_transaction__1f4d1fe8_fk_wallet_tr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_booking
    ADD CONSTRAINT slots_booking_payment_transaction__1f4d1fe8_fk_wallet_tr FOREIGN KEY (payment_transaction_id) REFERENCES public.wallet_transaction(transaction_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_booking slots_booking_schedule_id_688b7970_fk_slots_slotschedule_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_booking
    ADD CONSTRAINT slots_booking_schedule_id_688b7970_fk_slots_slotschedule_id FOREIGN KEY (schedule_id) REFERENCES public.slots_slotschedule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_booking slots_booking_wallet_id_3e3b637f_fk_wallet_wallet_wallet_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_booking
    ADD CONSTRAINT slots_booking_wallet_id_3e3b637f_fk_wallet_wallet_wallet_id FOREIGN KEY (wallet_id) REFERENCES public.wallet_wallet(wallet_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_slot_collaborators slots_slot_collabora_customuser_id_04c742ac_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slot_collaborators
    ADD CONSTRAINT slots_slot_collabora_customuser_id_04c742ac_fk_authentic FOREIGN KEY (customuser_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_slot_collaborators slots_slot_collaborators_slot_id_41e1f6c2_fk_slots_slot_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slot_collaborators
    ADD CONSTRAINT slots_slot_collaborators_slot_id_41e1f6c2_fk_slots_slot_id FOREIGN KEY (slot_id) REFERENCES public.slots_slot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_slot slots_slot_owner_id_903fd48f_fk_authentication_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slot
    ADD CONSTRAINT slots_slot_owner_id_903fd48f_fk_authentication_customuser_id FOREIGN KEY (owner_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_slot slots_slot_slot_type_id_2afde436_fk_slots_slottype_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slot
    ADD CONSTRAINT slots_slot_slot_type_id_2afde436_fk_slots_slottype_id FOREIGN KEY (slot_type_id) REFERENCES public.slots_slottype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: slots_slotschedule slots_slotschedule_slot_id_087c7c21_fk_slots_slot_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slots_slotschedule
    ADD CONSTRAINT slots_slotschedule_slot_id_087c7c21_fk_slots_slot_id FOREIGN KEY (slot_id) REFERENCES public.slots_slot(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_account_id_951f210e_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_account_id_951f210e_fk_socialacc FOREIGN KEY (account_id) REFERENCES public.socialaccount_socialaccount(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialtoken socialaccount_social_app_id_636a42d7_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialtoken
    ADD CONSTRAINT socialaccount_social_app_id_636a42d7_fk_socialacc FOREIGN KEY (app_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_site_id_2579dee5_fk_django_si; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_site_id_2579dee5_fk_django_si FOREIGN KEY (site_id) REFERENCES public.django_site(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialapp_sites socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialapp_sites
    ADD CONSTRAINT socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc FOREIGN KEY (socialapp_id) REFERENCES public.socialaccount_socialapp(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: socialaccount_socialaccount socialaccount_social_user_id_8146e70c_fk_authentic; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.socialaccount_socialaccount
    ADD CONSTRAINT socialaccount_social_user_id_8146e70c_fk_authentic FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_location wallet_location_location_type_id_03e38010_fk_wallet_lo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_location
    ADD CONSTRAINT wallet_location_location_type_id_03e38010_fk_wallet_lo FOREIGN KEY (location_type_id) REFERENCES public.wallet_locationtype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passcategory_allowed_location_types wallet_passcategory__locationtype_id_e49c1689_fk_wallet_lo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passcategory_allowed_location_types
    ADD CONSTRAINT wallet_passcategory__locationtype_id_e49c1689_fk_wallet_lo FOREIGN KEY (locationtype_id) REFERENCES public.wallet_locationtype(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passcategory_allowed_location_types wallet_passcategory__passcategory_id_c04f7a32_fk_wallet_pa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passcategory_allowed_location_types
    ADD CONSTRAINT wallet_passcategory__passcategory_id_c04f7a32_fk_wallet_pa FOREIGN KEY (passcategory_id) REFERENCES public.wallet_passcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passdetails_allowed_locations wallet_passdetails_a_location_id_417b4b4d_fk_wallet_lo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails_allowed_locations
    ADD CONSTRAINT wallet_passdetails_a_location_id_417b4b4d_fk_wallet_lo FOREIGN KEY (location_id) REFERENCES public.wallet_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passdetails_allowed_locations wallet_passdetails_a_passdetails_id_8d5ddd88_fk_wallet_pa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails_allowed_locations
    ADD CONSTRAINT wallet_passdetails_a_passdetails_id_8d5ddd88_fk_wallet_pa FOREIGN KEY (passdetails_id) REFERENCES public.wallet_passdetails(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passdetails wallet_passdetails_category_id_5a7d0ab9_fk_wallet_pa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails
    ADD CONSTRAINT wallet_passdetails_category_id_5a7d0ab9_fk_wallet_pa FOREIGN KEY (category_id) REFERENCES public.wallet_passcategory(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passdetails wallet_passdetails_from_location_id_b3ebddd6_fk_wallet_lo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails
    ADD CONSTRAINT wallet_passdetails_from_location_id_b3ebddd6_fk_wallet_lo FOREIGN KEY (from_location_id) REFERENCES public.wallet_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passdetails wallet_passdetails_to_location_id_e81ab599_fk_wallet_lo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails
    ADD CONSTRAINT wallet_passdetails_to_location_id_e81ab599_fk_wallet_lo FOREIGN KEY (to_location_id) REFERENCES public.wallet_location(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_passdetails wallet_passdetails_wallet_id_aa38a845_fk_wallet_wa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_passdetails
    ADD CONSTRAINT wallet_passdetails_wallet_id_aa38a845_fk_wallet_wa FOREIGN KEY (wallet_id) REFERENCES public.wallet_wallet(wallet_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_transaction wallet_transaction_from_wallet_id_cc4434bf_fk_wallet_wa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_transaction
    ADD CONSTRAINT wallet_transaction_from_wallet_id_cc4434bf_fk_wallet_wa FOREIGN KEY (from_wallet_id) REFERENCES public.wallet_wallet(wallet_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_transaction wallet_transaction_to_wallet_id_6fd62e93_fk_wallet_wa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_transaction
    ADD CONSTRAINT wallet_transaction_to_wallet_id_6fd62e93_fk_wallet_wa FOREIGN KEY (to_wallet_id) REFERENCES public.wallet_wallet(wallet_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_wallet wallet_wallet_parent_wallet_id_7a48dbf4_fk_wallet_wa; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_parent_wallet_id_7a48dbf4_fk_wallet_wa FOREIGN KEY (parent_wallet_id) REFERENCES public.wallet_wallet(wallet_id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_wallet wallet_wallet_user_id_8c75caaa_fk_authentication_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_user_id_8c75caaa_fk_authentication_customuser_id FOREIGN KEY (user_id) REFERENCES public.authentication_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

