# Generated by Django 5.2.5 on 2025-08-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_type',
            field=models.CharField(choices=[('main', 'Main'), ('pass', 'Pass'), ('vendor', 'Vendor')], max_length=20),
        ),
    ]
