# Generated by Django 5.2.5 on 2025-08-15 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_unique_main_wallet_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='wallet.locationtype')),
            ],
        ),
        migrations.CreateModel(
            name='PassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('allowed_location_types', models.ManyToManyField(blank=True, related_name='pass_categories', to='wallet.locationtype')),
            ],
        ),
        migrations.CreateModel(
            name='PassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('allowed_locations', models.ManyToManyField(blank=True, related_name='allowed_in_passes', to='wallet.location')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='wallet.passcategory')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_from', to='wallet.location')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passes_to', to='wallet.location')),
                ('wallet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pass_details', to='wallet.wallet')),
            ],
        ),
    ]
