# Generated by Django 5.2.5 on 2025-08-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_locationtype_location_passcategory_passdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
