# Generated by Django 5.2.5 on 2025-08-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_wallet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
