# Generated by Django 5.2.5 on 2025-08-15 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Users who can edit/manage this slot.', related_name='collaborating_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slot',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='slots/covers/'),
        ),
        migrations.AddField(
            model_name='slot',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_slots', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
