# Generated by Django 5.2.5 on 2025-08-16 04:35

import slots.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_slot_collaborators_slot_cover_image_slot_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='action',
            field=models.JSONField(blank=True, encoder=slots.encoders.PrettyJSONEncoder, null=True, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='description',
            field=models.JSONField(blank=True, encoder=slots.encoders.PrettyJSONEncoder, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='fields',
            field=models.JSONField(blank=True, encoder=slots.encoders.PrettyJSONEncoder, null=True, verbose_name='fields'),
        ),
    ]
