version: "3.9"
services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - devnet
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://appuser:apppass@db:5432/appdb?sslmode=disable

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5432:5432"
    networks:
      - devnet

networks:
  devnet:
